---
version: 2
sources:
- name: "psrc"
  database: "database"
  schema: "schema"
  tables:
  - name: "ptab"
    identifier: "table"
    columns:
    - name: "cents"
      dataType:
        type: "Integer"
    - name: "id"
      dataType:
        type: "String"
    - name: "first_name"
      dataType:
        type: "String"
    - name: "last_name"
      dataType:
        type: "String"
